services:
  app:
    build: .
    container_name: guestbook_app
    ports:
      - "8080:5000"
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

    networks:
      - AppNet

  db:
    image: postgres:15-alpine
    container_name: guestbook_db
    ports:
      - "5432:5432"
    
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    
    volumes:
      - db-data:/var/lib/postgresql/data

    networks:
      - AppNet

volumes:
  db-data:

networks:
  AppNet:
    driver: bridge